// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZ0ZohLWCt1NEnLzpx9vy0RUdoit8R53w',
    appId: '1:563531037147:web:3597fb9e097ae270e64ffe',
    messagingSenderId: '563531037147',
    projectId: 'foodpanda-clone-bacba',
    authDomain: 'foodpanda-clone-bacba.firebaseapp.com',
    storageBucket: 'foodpanda-clone-bacba.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0aI23Z7e7Nuby_Z5XdEvVTYl9C_JL8RU',
    appId: '1:563531037147:android:11d026fcfdd01635e64ffe',
    messagingSenderId: '563531037147',
    projectId: 'foodpanda-clone-bacba',
    storageBucket: 'foodpanda-clone-bacba.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCabtISHKuWtIP13Y5jKWotGWvkbvE1S5o',
    appId: '1:563531037147:ios:75f93ddf9a211f90e64ffe',
    messagingSenderId: '563531037147',
    projectId: 'foodpanda-clone-bacba',
    storageBucket: 'foodpanda-clone-bacba.appspot.com',
    iosBundleId: 'com.example.foodpandaClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCabtISHKuWtIP13Y5jKWotGWvkbvE1S5o',
    appId: '1:563531037147:ios:400e3fb4a8855e40e64ffe',
    messagingSenderId: '563531037147',
    projectId: 'foodpanda-clone-bacba',
    storageBucket: 'foodpanda-clone-bacba.appspot.com',
    iosBundleId: 'com.example.foodpandaClone.RunnerTests',
  );
}
